### PR TITLE
update/prune docs according to jord's feedback

### PR DESCRIPTION
**Pull request by arentweall**
fyi @jordanlesich @UI369 

making some of the re-orgs / updates that we discussed

### CODE REVIEW

**Comment by jonathanprozzi** [comment]
Updates look good but seeing some changes to the package versions. Did you intentionally downgrade nextra?

Should pause on merge until we see what's up with that since the diff is like 10k lines.

**Comment by arentweall** [comment]
Oh that's weird. 

Sorry first time using Nextra - I might have done that while following terminal instructions. Let me know how we can rectify this!

**Comment by jonathanprozzi** [comment]
No prob! Can take a deeper look and see what's up

**Comment by arentweall** [comment]
Bumping this up - checking if there are any updates or if I can help sort things out :)

**Comment by UI369** [comment]
@jonathanprozzi Bump, any update on this? What do we need to do to get this merged?  

There's another wave of changes ready coming and want to make sure we get these issues resolved.  Anything I can do to help?

**Pull request merged**
